### ISSUE TITLE
Add UBC email to personal settings to ensure commits are properly tied to each person.

### ISSUE THREAD

**Issue by alto10002** [UBC-MDS/522_group_27#5]
If certain commits werent being tied to a user, this can be fixed by add our UBC student emails so our respective accounts.

**Comment by michael-gelfand** [comment]
All users emails have been updated and now only 4 users are contributing all tied to a GitHub account.

<img width="202" alt="image" src="https://github.com/user-attachments/assets/81b7aaac-4a88-4752-8c53-8bfbfa70017d">

**Comment by michael-gelfand** [comment]
Closed
