### ISSUE TITLE
Add data validation checks to the data analysis.

### ISSUE THREAD

**Issue by dominic-lam** [UBC-MDS/522_group_27#7]
13.3.1 Data validation checklist

1. Correct data file format
2. Correct column names
3. No empty observations
4. Missingness not beyond expected threshold
5. Correct data types in each column
6. No duplicate observations
7. No outlier or anomalous values
8. Correct category levels (i.e., no string mismatches or single values)
9. Target/response variable follows expected distribution
10. No anomalous correlations between target/response variable and features/explanatory variables
11. No anomalous correlations between features/explanatory variables

**Comment by dominic-lam** [comment]
We added a comment with the below text for each of the checks we did

Correct data file format ✅
Correct column names ✅
No empty observations✅

**Comment by michael-gelfand** [comment]
Completed with pull request #15
